# Generated by Django 5.1.6 on 2025-02-21 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0007_alter_pedido_forma_pagamento_alter_produto_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='forma_pagamento',
            new_name='metodo_pagamento',
        ),
    ]
