# Generated by Django 5.1.6 on 2025-03-21 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0011_alter_pedido_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoEntregue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itens', models.TextField()),
                ('entregue_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.cliente')),
            ],
        ),
    ]
