# Generated by Django 5.1.6 on 2025-04-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0016_pedido_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo_consumo',
            field=models.CharField(choices=[('local', 'Comer no local'), ('viagem', 'Levar para viagem')], default='local', max_length=10),
        ),
    ]
