# Generated by Django 5.1.6 on 2025-04-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0017_pedido_tipo_consumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoentregue',
            name='metodo_pagamento',
            field=models.CharField(choices=[('PIX', 'PIX'), ('Dinheiro', 'Dinheiro')], default='PIX', max_length=10),
        ),
        migrations.AddField(
            model_name='pedidoentregue',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
