# Generated by Django 5.1.6 on 2025-04-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0018_pedidoentregue_metodo_pagamento_pedidoentregue_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='liberado_para_cozinha',
            field=models.BooleanField(default=False),
        ),
    ]
