# Generated by Django 5.1.6 on 2025-04-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0019_pedido_liberado_para_cozinha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='liberado_para_caixa',
            field=models.BooleanField(default=False),
        ),
    ]
