# Generated by Django 5.1.6 on 2025-05-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0021_pedido_time_liberado_para_cozinha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='time_liberado_para_cozinha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
