# Generated by Django 5.1.6 on 2025-05-04 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0022_alter_pedido_time_liberado_para_cozinha'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCancelado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itens', models.TextField()),
                ('metodo_pagamento', models.CharField(max_length=100)),
                ('cancelado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedido.cliente')),
            ],
        ),
    ]
