# Generated by Django 5.1.6 on 2025-07-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0024_pedido_time_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Salgados', 'Salgados'), ('Doces', 'Doces'), ('Bebidas', 'Bebidas'), ('Caldos', 'Caldos')], default='Outros', max_length=20),
        ),
    ]
