# Generated by Django 5.1.6 on 2025-07-11 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0026_alter_produto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('fixo', 'Fixo'), ('opcional', 'Com opções')], default='fixo', max_length=10)),
                ('produto_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='combo', to='pedido.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedido.combo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.produto')),
            ],
        ),
        migrations.CreateModel(
            name='OpcaoCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Salgados', 'Salgados'), ('Doces', 'Doces'), ('Bebidas', 'Bebidas'), ('Caldos', 'Caldos'), ('Combos', 'Combos')], max_length=20)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='pedido.combo')),
            ],
        ),
    ]
