# Generated by Django 5.1.6 on 2025-07-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0027_combo_itemcombo_opcaocombo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcombo',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
