# Generated by Django 5.1.6 on 2025-07-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0028_itemcombo_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='escolhas_combo',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
