# Generated by Django 5.1.6 on 2025-08-22 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0029_itempedido_escolhas_combo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcaocombo',
            name='categoria',
            field=models.CharField(choices=[('Salgado', 'Salgado'), ('Doce', 'Doce'), ('Bebida', 'Bebida'), ('Caldo', 'Caldo'), ('Combo', 'Combo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Salgado', 'Salgado'), ('Doce', 'Doce'), ('Bebida', 'Bebida'), ('Caldo', 'Caldo'), ('Combo', 'Combo')], default='Outros', max_length=20),
        ),
    ]
