# Generated by Django 5.1.6 on 2025-09-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0030_alter_opcaocombo_categoria_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcaocombo',
            name='categoria',
            field=models.CharField(choices=[('Salgados', 'Salgados'), ('Doces', 'Doces'), ('Bebidas', 'Bebidas'), ('Caldos', 'Caldos'), ('Combos', 'Combos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('Salgados', 'Salgados'), ('Doces', 'Doces'), ('Bebidas', 'Bebidas'), ('Caldos', 'Caldos'), ('Combos', 'Combos')], default='Outros', max_length=20),
        ),
    ]
