# Generated by Django 5.1.6 on 2025-09-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0031_alter_opcaocombo_categoria_alter_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='tipo',
            field=models.CharField(choices=[('fixo', 'Fixo'), ('opcional', 'Com opções'), ('fixo_opcional', 'Fixo + opções')], default='fixo', max_length=15),
        ),
    ]
